[project]
name = "train-ai-to-play-snake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.0.2",
    "matplotlib>=3.10.1",
    "pygame>=2.6.1",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
]
